
# This file is automatically generated, you probably don't want to edit this

pathjOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathjOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            endogenous = NULL,
            factors = NULL,
            covs = NULL,
            ciType = "standard",
            ciWidth = 95,
            bootN = 1000,
            contrasts = NULL,
            showRealNames = TRUE,
            showContrastCode = FALSE,
            endogenousTerms = list(
                list()), ...) {

            super$initialize(
                package="pathj",
                name="pathj",
                requiresData=TRUE,
                ...)

            private$..endogenous <- jmvcore::OptionVariables$new(
                "endogenous",
                endogenous,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..ciType <- jmvcore::OptionList$new(
                "ciType",
                ciType,
                options=list(
                    "standard",
                    "bca",
                    "perc",
                    "norm",
                    "none"),
                default="standard")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..bootN <- jmvcore::OptionNumber$new(
                "bootN",
                bootN,
                min=50,
                default=1000)
            private$..contrasts <- jmvcore::OptionArray$new(
                "contrasts",
                contrasts,
                items="(factors)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "contrasts",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "simple",
                                "deviation",
                                "dummy",
                                "difference",
                                "helmert",
                                "repeated",
                                "polynomial"),
                            default="simple"))))
            private$..showRealNames <- jmvcore::OptionBool$new(
                "showRealNames",
                showRealNames,
                default=TRUE)
            private$..showContrastCode <- jmvcore::OptionBool$new(
                "showContrastCode",
                showContrastCode,
                default=FALSE)
            private$..endogenousTerms <- jmvcore::OptionArray$new(
                "endogenousTerms",
                endogenousTerms,
                default=list(
                    list()),
                template=jmvcore::OptionTerms$new(
                    "endogenousTerms",
                    NULL))

            self$.addOption(private$..endogenous)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..ciType)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..bootN)
            self$.addOption(private$..contrasts)
            self$.addOption(private$..showRealNames)
            self$.addOption(private$..showContrastCode)
            self$.addOption(private$..endogenousTerms)
        }),
    active = list(
        endogenous = function() private$..endogenous$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        ciType = function() private$..ciType$value,
        ciWidth = function() private$..ciWidth$value,
        bootN = function() private$..bootN$value,
        contrasts = function() private$..contrasts$value,
        showRealNames = function() private$..showRealNames$value,
        showContrastCode = function() private$..showContrastCode$value,
        endogenousTerms = function() private$..endogenousTerms$value),
    private = list(
        ..endogenous = NA,
        ..factors = NA,
        ..covs = NA,
        ..ciType = NA,
        ..ciWidth = NA,
        ..bootN = NA,
        ..contrasts = NA,
        ..showRealNames = NA,
        ..showContrastCode = NA,
        ..endogenousTerms = NA)
)

pathjResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathjResults",
    inherit = jmvcore::Group,
    active = list(
        info = function() private$.items[["info"]],
        pathmodelgroup = function() private$.items[["pathmodelgroup"]],
        models = function() private$.items[["models"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Path Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="info",
                title="Models Info",
                columns=list(
                    list(
                        `name`="info", 
                        `type`="text", 
                        `title`="", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="specs", 
                        `type`="text", 
                        `title`=""),
                    list(
                        `name`="value", 
                        `type`="text", 
                        `title`="")),
                clearWith=NULL,
                refs="pathj"))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    pathmodel = function() private$.items[["pathmodel"]],
                    pathnotes = function() private$.items[["pathnotes"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="pathmodelgroup",
                            title="Path Model",
                            clearWith=list(
                    "endogenous"))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="pathmodel",
                            title="Model Diagram",
                            width=600,
                            height=500,
                            renderFun=".showDiagram",
                            clearWith=list(
                                "endogenous"),
                            refs="diagram"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="pathnotes",
                            title="",
                            visible=FALSE,
                            columns=list(
                                list(
                                    `name`="info", 
                                    `type`="text", 
                                    `title`="Model diagram notes"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    main = function() private$.items[["main"]],
                    contrastCodeTables = function() private$.items[["contrastCodeTables"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="models",
                            title="Estimates",
                            clearWith=list(
                    "endogenous"))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="main",
                            title="Indirect and Total Effects",
                            refs="lavaan",
                            clearWith=list(
                                "endogenous",
                                "ciType"),
                            columns=list(
                                list(
                                    `name`="type", 
                                    `title`="Type", 
                                    `type`="text", 
                                    `combineBelow`=TRUE),
                                list(
                                    `name`="source", 
                                    `title`="Effect", 
                                    `type`="text"),
                                list(
                                    `name`="label", 
                                    `title`="Contrasts", 
                                    `visible`=FALSE, 
                                    `type`="text"),
                                list(
                                    `name`="est", 
                                    `title`="Estimate", 
                                    `type`="number"),
                                list(
                                    `name`="se", 
                                    `title`="SE", 
                                    `type`="number"),
                                list(
                                    `name`="ci.lower", 
                                    `type`="number", 
                                    `title`="Lower", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="ci.upper", 
                                    `type`="number", 
                                    `title`="Upper", 
                                    `visible`="(ciType:standard || ciType:perc || ciType:norm || ciType:bca)"),
                                list(
                                    `name`="std.all", 
                                    `type`="number", 
                                    `title`="\u03B2", 
                                    `visible`="(tableOptions:beta)"),
                                list(
                                    `name`="z", 
                                    `title`="z", 
                                    `type`="number"),
                                list(
                                    `name`="pvalue", 
                                    `title`="p", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="contrastCodeTables",
                            title="Contrast Coefficients",
                            visible="(showContrastCode)",
                            clearWith=list(
                                "contrasts",
                                "showContrastCode"),
                            template=jmvcore::Table$new(
                                options=options,
                                title="$key",
                                visible="(showContrastCode)",
                                columns=list(
                                    list(
                                        `name`="rnames", 
                                        `title`="Name", 
                                        `type`="text"),
                                    list(
                                        `name`="clabs", 
                                        `title`="Contrast", 
                                        `type`="text")))))}))$new(options=options))}))

pathjBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "pathjBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "pathj",
                name = "pathj",
                version = c(0,0,1),
                options = options,
                results = pathjResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Path Analysis
#'
#' Path Analysis
#' @param data the data as a data frame
#' @param endogenous a vector of strings naming the mediators from \code{data}
#' @param factors a vector of strings naming the fixed factors from
#'   \code{data}
#' @param covs a vector of strings naming the covariates from \code{data}
#' @param ciType Choose the confidence interval type
#' @param ciWidth a number between 50 and 99.9 (default: 95) specifying the
#'   confidence interval width for the parameter estimates
#' @param bootN number of bootstrap samples for estimating confidence
#'   intervals
#' @param contrasts a list of lists specifying the factor and type of contrast
#'   to use, one of \code{'deviation'}, \code{'simple'}, \code{'difference'},
#'   \code{'helmert'}, \code{'repeated'} or \code{'polynomial'}
#' @param showRealNames \code{TRUE} or \code{FALSE} (default), provide raw
#'   names of the contrasts variables
#' @param showContrastCode \code{TRUE} or \code{FALSE} (default), provide
#'   contrast coefficients tables
#' @param endogenousTerms a list of lists specifying the models for with the
#'   mediators as dependent variables.
#' @param formula (optional) the formula to use, see the examples
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$info} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$pathmodelgroup$pathmodel} \tab \tab \tab \tab \tab a path model \cr
#'   \code{results$pathmodelgroup$pathnotes} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$models$contrastCodeTables} \tab \tab \tab \tab \tab an array of contrast coefficients tables \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$info$asDF}
#'
#' \code{as.data.frame(results$info)}
#'
#' @export
pathj <- function(
    data,
    endogenous = NULL,
    factors = NULL,
    covs = NULL,
    ciType = "standard",
    ciWidth = 95,
    bootN = 1000,
    contrasts = NULL,
    showRealNames = TRUE,
    showContrastCode = FALSE,
    endogenousTerms = list(
                list()),
    formula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("pathj requires jmvcore to be installed (restart may be required)")

    if ( ! missing(formula)) {
        if (missing(dep))
            dep <- pathjClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="dep")
        if (missing(factors))
            factors <- pathjClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="factors")
        if (missing(covs))
            covs <- pathjClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="covs")
        if (missing(endogenous))
            endogenous <- pathjClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="endogenous")
        if (missing(endogenousTerms))
            endogenousTerms <- pathjClass$private_methods$.marshalFormula(
                formula=formula,
                data=`if`( ! missing(data), data, NULL),
                name="endogenousTerms")
    }

    if ( ! missing(endogenous)) endogenous <- jmvcore::resolveQuo(jmvcore::enquo(endogenous))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(endogenous), endogenous, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- pathjOptions$new(
        endogenous = endogenous,
        factors = factors,
        covs = covs,
        ciType = ciType,
        ciWidth = ciWidth,
        bootN = bootN,
        contrasts = contrasts,
        showRealNames = showRealNames,
        showContrastCode = showContrastCode,
        endogenousTerms = endogenousTerms)

    analysis <- pathjClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

